### ISSUE TITLE
Checksum incorrect?

### ISSUE THREAD

**Issue by vincentkersten** [practical-solutions/dokuwiki-xlsconv#1]
Hello, 
just tried to insert your plugin to test it, but:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/5429401/84374757-bff7d100-abde-11ea-8b6f-3e2f22e9d069.png">

there seems to be an error with "Header does not match it's checksum" any idea how to fix that?

**Comment by practical-solutions** [comment]
Try:

https://github.com/practical-solutions/dokuwiki-xlsconv/archive/master.zip

instead.

**Comment by vincentkersten** [comment]
Thank was Quick :)
I tried that, and now it installs 👍 

Thank yo uso much!
